# -*- coding: utf-8 -*-
"""Classic Abaqus FEA example: 3D cantilever beam static bending.

Units: N, mm, MPa.
Geometry: L=100 mm, W=10 mm, H=10 mm.
Material: steel-like linear elastic, E=210000 MPa, nu=0.3.
Boundary/loading: left end fixed; right end face loaded by a vertical surface
traction with total force equivalent to F_y = -1000 N.
"""

from __future__ import print_function

import json
import os

from abaqus import mdb, session
from abaqusConstants import *
import mesh
import regionToolset
from odbAccess import openOdb


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WORK_DIR = os.environ.get(
    "ABAQUS_EXAMPLE_WORK_DIR",
    os.path.join(SCRIPT_DIR, "output", "classic_cantilever"),
)
MODEL_NAME = "Classic_Cantilever_Beam"
JOB_NAME = "classic_cantilever_beam"


def ensure_dir(path):
    if not os.path.isdir(path):
        os.makedirs(path)


def build_model():
    ensure_dir(WORK_DIR)
    os.chdir(WORK_DIR)

    if MODEL_NAME in mdb.models:
        del mdb.models[MODEL_NAME]

    model = mdb.Model(name=MODEL_NAME)

    length = 100.0
    height = 10.0
    width = 10.0

    sketch = model.ConstrainedSketch(name="beam_profile", sheetSize=160.0)
    sketch.rectangle(point1=(0.0, -height / 2.0), point2=(length, height / 2.0))

    part = model.Part(name="Beam", dimensionality=THREE_D, type=DEFORMABLE_BODY)
    part.BaseSolidExtrude(sketch=sketch, depth=width)
    del model.sketches["beam_profile"]

    material = model.Material(name="Steel_Elastic")
    material.Elastic(table=((210000.0, 0.30),))

    section = model.HomogeneousSolidSection(name="Steel_Section", material="Steel_Elastic")
    part.SectionAssignment(
        region=regionToolset.Region(cells=part.cells[:]),
        sectionName="Steel_Section",
    )

    part.seedPart(size=2.5, deviationFactor=0.1, minSizeFactor=0.1)
    part.setMeshControls(regions=part.cells[:], elemShape=HEX, technique=STRUCTURED)
    elem_type = mesh.ElemType(elemCode=C3D8R, elemLibrary=STANDARD)
    part.setElementType(regions=(part.cells[:],), elemTypes=(elem_type,))
    part.generateMesh()

    assembly = model.rootAssembly
    assembly.DatumCsysByDefault(CARTESIAN)
    inst = assembly.Instance(name="Beam-1", part=part, dependent=ON)

    eps = 1.0e-3
    left_faces = inst.faces.getByBoundingBox(
        xMin=-eps, xMax=eps,
        yMin=-height, yMax=height,
        zMin=-eps, zMax=width + eps,
    )
    right_faces = inst.faces.getByBoundingBox(
        xMin=length - eps, xMax=length + eps,
        yMin=-height, yMax=height,
        zMin=-eps, zMax=width + eps,
    )

    assembly.Set(name="FIXED_END", faces=left_faces)
    assembly.Surface(name="LOADED_END", side1Faces=right_faces)

    model.StaticStep(name="Bending", previous="Initial", nlgeom=OFF)

    model.EncastreBC(
        name="Fixed_Left_End",
        createStepName="Initial",
        region=assembly.sets["FIXED_END"],
    )

    # Abaqus' coupling API differs between installations. A GENERAL surface
    # traction on the free end is robust and keeps the resultant load classical.
    model.SurfaceTraction(
        name="Downward_End_Traction_1000N",
        createStepName="Bending",
        region=assembly.surfaces["LOADED_END"],
        magnitude=10.0,
        directionVector=((0.0, 0.0, 0.0), (0.0, -1.0, 0.0)),
        distributionType=UNIFORM,
        field="",
        localCsys=None,
        traction=GENERAL,
        follower=OFF,
    )

    mdb.Job(
        name=JOB_NAME,
        model=MODEL_NAME,
        description="Classic 3D cantilever beam bending benchmark generated by Codex.",
        type=ANALYSIS,
        memory=90,
        memoryUnits=PERCENTAGE,
        numCpus=2,
        numDomains=2,
    )

    mdb.saveAs(pathName=os.path.join(WORK_DIR, JOB_NAME + ".cae"))


def run_job():
    job = mdb.jobs[JOB_NAME]
    job.submit(consistencyChecking=OFF)
    job.waitForCompletion()


def extract_results():
    odb_path = os.path.join(WORK_DIR, JOB_NAME + ".odb")
    odb = openOdb(path=odb_path, readOnly=True)
    step = odb.steps["Bending"]
    frame = step.frames[-1]

    u_field = frame.fieldOutputs["U"]
    s_field = frame.fieldOutputs["S"]

    max_u = 0.0
    max_u_node = None
    for value in u_field.values:
        mag = (value.data[0] ** 2 + value.data[1] ** 2 + value.data[2] ** 2) ** 0.5
        if mag > max_u:
            max_u = mag
            max_u_node = value.nodeLabel

    max_mises = 0.0
    max_mises_element = None
    for value in s_field.values:
        if value.mises > max_mises:
            max_mises = value.mises
            max_mises_element = value.elementLabel

    summary = {
        "case": "Classic 3D cantilever beam static bending",
        "units": "N-mm-MPa",
        "geometry_mm": {"length": 100.0, "width": 10.0, "height": 10.0},
        "material": {"E_MPa": 210000.0, "nu": 0.30},
        "load": {"free_end_surface_traction_MPa": 10.0, "equivalent_FY_N": -1000.0},
        "boundary_condition": "left end encastre; right end vertical GENERAL surface traction",
        "mesh": {"element_type": "C3D8R", "global_size_mm": 2.5},
        "results": {
            "max_displacement_mm": max_u,
            "max_displacement_node": max_u_node,
            "max_mises_stress_MPa": max_mises,
            "max_mises_element": max_mises_element,
        },
        "files": {
            "cae": os.path.join(WORK_DIR, JOB_NAME + ".cae"),
            "odb": odb_path,
        },
    }

    odb.close()

    result_path = os.path.join(WORK_DIR, "result_summary.json")
    with open(result_path, "w") as f:
        json.dump(summary, f, indent=2)

    print("RESULT_SUMMARY_JSON=" + json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    build_model()
    run_job()
    extract_results()
