# -*- coding: utf-8 -*-
"""Classic Abaqus tensile simulation: 3D rectangular steel bar.

Units: N, mm, MPa.
Geometry: L=100 mm, W=10 mm, H=10 mm.
Material: linear elastic steel, E=210000 MPa, nu=0.3.
Boundary/loading: left end fixed; right end prescribed axial displacement
U1 = 1 mm, giving nominal engineering strain = 0.01.
"""

from __future__ import print_function

import json
import os

from abaqus import mdb
from abaqusConstants import *
import mesh
import regionToolset
from odbAccess import openOdb


try:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    SCRIPT_DIR = os.getcwd()

WORK_DIR = os.environ.get(
    "ABAQUS_TENSILE_WORK_DIR",
    os.path.join(SCRIPT_DIR, "output", "classic_tensile"),
)
MODEL_NAME = "Classic_Tensile_Bar"
JOB_NAME = "classic_tensile_bar"


def ensure_dir(path):
    if not os.path.isdir(path):
        os.makedirs(path)


def build_model():
    ensure_dir(WORK_DIR)
    os.chdir(WORK_DIR)

    if MODEL_NAME in mdb.models:
        del mdb.models[MODEL_NAME]

    model = mdb.Model(name=MODEL_NAME)

    length = 100.0
    width = 10.0
    height = 10.0
    imposed_u1 = 1.0

    sketch = model.ConstrainedSketch(name="bar_profile", sheetSize=160.0)
    sketch.rectangle(point1=(0.0, -height / 2.0), point2=(length, height / 2.0))

    part = model.Part(name="Tensile_Bar", dimensionality=THREE_D, type=DEFORMABLE_BODY)
    part.BaseSolidExtrude(sketch=sketch, depth=width)
    del model.sketches["bar_profile"]

    material = model.Material(name="Steel_Elastic")
    material.Elastic(table=((210000.0, 0.30),))

    section = model.HomogeneousSolidSection(name="Steel_Section", material="Steel_Elastic")
    part.SectionAssignment(
        region=regionToolset.Region(cells=part.cells[:]),
        sectionName="Steel_Section",
    )

    part.seedPart(size=5.0, deviationFactor=0.1, minSizeFactor=0.1)
    part.setMeshControls(regions=part.cells[:], elemShape=HEX, technique=STRUCTURED)
    elem_type = mesh.ElemType(elemCode=C3D8R, elemLibrary=STANDARD)
    part.setElementType(regions=(part.cells[:],), elemTypes=(elem_type,))
    part.generateMesh()

    assembly = model.rootAssembly
    assembly.DatumCsysByDefault(CARTESIAN)
    inst = assembly.Instance(name="Tensile_Bar-1", part=part, dependent=ON)

    eps = 1.0e-3
    left_faces = inst.faces.getByBoundingBox(
        xMin=-eps, xMax=eps,
        yMin=-height, yMax=height,
        zMin=-eps, zMax=width + eps,
    )
    right_nodes = inst.nodes.getByBoundingBox(
        xMin=length - eps, xMax=length + eps,
        yMin=-height, yMax=height,
        zMin=-eps, zMax=width + eps,
    )

    assembly.Set(name="FIXED_END", faces=left_faces)
    assembly.Set(name="PULLED_END_NODES", nodes=right_nodes)

    model.StaticStep(name="Tension", previous="Initial", nlgeom=OFF)

    model.EncastreBC(
        name="Fixed_Left_End",
        createStepName="Initial",
        region=assembly.sets["FIXED_END"],
    )
    model.DisplacementBC(
        name="Right_End_U1_1mm",
        createStepName="Tension",
        region=assembly.sets["PULLED_END_NODES"],
        u1=imposed_u1,
        u2=UNSET,
        u3=UNSET,
        ur1=UNSET,
        ur2=UNSET,
        ur3=UNSET,
    )

    mdb.Job(
        name=JOB_NAME,
        model=MODEL_NAME,
        description="Classic 3D tensile bar benchmark generated by Codex.",
        type=ANALYSIS,
        memory=90,
        memoryUnits=PERCENTAGE,
        numCpus=2,
        numDomains=2,
    )

    mdb.saveAs(pathName=os.path.join(WORK_DIR, JOB_NAME + ".cae"))


def run_job():
    job = mdb.jobs[JOB_NAME]
    job.submit(consistencyChecking=OFF)
    job.waitForCompletion()


def extract_results():
    length = 100.0
    area = 100.0
    imposed_u1 = 1.0

    odb_path = os.path.join(WORK_DIR, JOB_NAME + ".odb")
    odb = openOdb(path=odb_path, readOnly=True)
    step = odb.steps["Tension"]
    frame = step.frames[-1]

    stress = frame.fieldOutputs["S"]
    displacement = frame.fieldOutputs["U"]
    reaction = frame.fieldOutputs["RF"]
    pulled_nodes = odb.rootAssembly.nodeSets["PULLED_END_NODES"]

    total_rf1 = 0.0
    for value in reaction.getSubset(region=pulled_nodes).values:
        total_rf1 += value.data[0]

    s11_total = 0.0
    s11_count = 0
    max_mises = 0.0
    for value in stress.values:
        s11_total += value.data[0]
        s11_count += 1
        if value.mises > max_mises:
            max_mises = value.mises

    max_u1 = 0.0
    for value in displacement.values:
        if abs(value.data[0]) > max_u1:
            max_u1 = abs(value.data[0])

    engineering_strain = imposed_u1 / length
    nominal_stress = abs(total_rf1) / area
    apparent_modulus = nominal_stress / engineering_strain
    average_s11 = s11_total / float(s11_count)

    summary = {
        "case": "Classic 3D tensile bar, displacement-controlled static tension",
        "units": "N-mm-MPa",
        "geometry_mm": {"length": length, "width": 10.0, "height": 10.0, "area": area},
        "material": {"E_MPa": 210000.0, "nu": 0.30},
        "load": {"right_end_prescribed_U1_mm": imposed_u1},
        "boundary_condition": "left end encastre; right end U1=1 mm, lateral DOF free",
        "mesh": {"element_type": "C3D8R", "global_size_mm": 5.0},
        "results": {
            "engineering_strain": float(engineering_strain),
            "total_reaction_force_N": float(total_rf1),
            "nominal_stress_MPa": float(nominal_stress),
            "apparent_modulus_MPa": float(apparent_modulus),
            "average_S11_MPa": float(average_s11),
            "max_U1_mm": float(max_u1),
            "max_mises_stress_MPa": float(max_mises),
        },
        "files": {
            "cae": os.path.join(WORK_DIR, JOB_NAME + ".cae"),
            "odb": odb_path,
        },
    }

    odb.close()

    result_path = os.path.join(WORK_DIR, "result_summary.json")
    with open(result_path, "w") as f:
        json.dump(summary, f, indent=2)

    print("RESULT_SUMMARY_JSON=" + json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    build_model()
    run_job()
    extract_results()
